wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: green
      normal: gray
    checked: yellow
    highlight: 
      fore: black
      back: gray
    rows:
      even: yellow
      odd: white
  grid:
    # How _wide_ the columns are, in terminal characters. In this case we have
    # four columns, each of which are 35 characters wide.
    columns: [35, 35, 35, 35]
    # How _high_ the rows are, in terminal lines. In this case we have four rows
    # that support ten line of text and one of four.
    rows: [10, 10, 10, 10, 4]
  refreshInterval: 1
  openFileUtil: "open"
  mods:
    # You can have multiple widgets of the same type.
    # The "key" is the name of the widget and the type is the actual
    # widget you want to implement.
    ip:
      type: ipinfo
      title: "My IP"
      colors:
        name: "lightblue"
        value: "white"
      enabled: true
      position:
        top: 1
        left: 0
        height: 1
        width: 1
      refreshInterval: 150
    news:
      type: hackernews
      title: "HackerNews"
      enabled: true
      numberOfStories: 20
      position:
        top: 0
        left: 1
        height: 3
        width: 3
      storyType: top
      refreshInterval: 900
    resources:
      type: resourceusage
      enabled: true
      position:
        top: 0
        left: 0
        height: 1
        width: 1
      refreshInterval: 1
    disks:
      type: cmdrunner
      cmd: "df"
      args: ["-h"]
      enabled: true
      position:
        top: 3
        left: 0
        height: 2
        width: 2
      refreshInterval: 600
    transmission:
      enabled: true
      host: "kodi"
      position:
        top: 3
        left: 2
        width: 2
        height: 2
      refreshInterval: 10
