#!/bin/bash
# Program launcher for sway
# intended to run in terminal


list_options() {
  # open windows
  swaymsg -t get_tree | jq 'def get_win($ws): 
            recurse(.nodes[]?) | 
              select(.type? == "con" and ( .app_id? != null or .window_properties? != null )) | 
              "ws "+ $ws + ": " + (if .app_id? != null then .app_id else .window_properties.instance end) + " " + .name + " id=" + (.id | tostring); 
          recurse(.nodes[]?) | select(.type? == "workspace") | get_win(.name)'
  # executables, available from PATH
  echo -n "$PATH" | xargs -d : -I{} -r -- find -L {} -maxdepth 1 -mindepth 1 -type f -executable -printf "%f\n" | sort -u  
}

prompt_user() {
  list_options | fzf --reverse --border --tiebreak=index -e --print-query --expect=ctrl-space
}


################################
#   Main starts here
################################

#declare $(parse_input) >> /dev/null # reduce output in case of cancelled input
INPUT_ARGS=(QUERY X_APP MATCH)

i=0
while read line
do
  eval "${INPUT_ARGS[i++]}='$line'"
done <<< $(prompt_user)

# check if should focus another window
win_id=`echo $MATCH | sed -n 's/^"ws \w\+: [^ ]\+ .* id=\([0-9]\+\)"$/\1/p'`

if [[ ! -z "$win_id" ]]
then
  swaymsg "[con_id = $win_id] focus"
  exit
fi

if [[ -z "$MATCH" ]]
then # user cancelled, or custom command 
  if [[ -z "$QUERY" ]]
  then
    exit # user cancelled
  fi

  MATCH="$QUERY"
fi

swaymsg "exec $(if [[ -z "$X_APP" ]]; then echo \$launch-native; fi) $MATCH"
